### ISSUE TITLE
RDP - Credentials are asking Twice 

### ISSUE THREAD

**Issue by subu1979** [Devolutions/RdpCredentialProvider#2]
Hi

After installation, when I try to log in via mstsc.exe, after authentication, again it's asking for credentials.

**Comment by awakecoding** [comment]
This is reference code to get started writing a credential provider for RDP - it is not really functional as is and should not be installed for production use. Please uninstall, it is unsupported.

**Comment by subu1979** [comment]
Thanks for the information.
